### ISSUE TITLE
Invalid thumbprint for GitLab.com

### ISSUE THREAD

**Issue by Vrtak-CZ** [terraform-module/terraform-aws-gitlab-oidc-provider#25]
### Steps to Reproduce:
```
module "aws_gitlab_oidc_infra" {
  source  = "terraform-module/gitlab-oidc-provider/aws"
  version = "1.0.0"

  create_oidc_provider = true
  create_oidc_role     = true

  repositories              = ["project_path:REDACTED/REDACTED"]
  oidc_role_attach_policies = ["arn:aws:iam::aws:policy/AdministratorAccess"]
  role_name                 = "gitlab-oidc"
}
```

### Expected Result:
```
STS=($(aws sts assume-role-with-web-identity --role-arn ${ROLE_ARN} --role-session-name "GitLabRunner-${CI_PROJECT_ID}-${CI_PIPELINE_ID}" --web-identity-token $CI_JOB_JWT_V2 --duration-seconds 3600 --query 'Credentials.[AccessKeyId,SecretAccessKey,SessionToken]' --output text))

without error
```

### Actual Result:
```
$ STS=($(aws sts assume-role-with-web-identity --role-arn ${ROLE_ARN} --role-session-name "GitLabRunner-${CI_PROJECT_ID}-${CI_PIPELINE_ID}" --web-identity-token $CI_JOB_JWT_V2 --duration-seconds 3600 --query 'Credentials.[AccessKeyId,SecretAccessKey,SessionToken]' --output text))
An error occurred (InvalidIdentityToken) when calling the AssumeRoleWithWebIdentity operation: OpenIDConnect provider's HTTPS certificate doesn't match configured thumbprint
```

### Environment:
1.0.0 version of this module

### Additional Context:
Its because `https://gitlab.com` has different certificate than `https://gitlab.com/.well-known/openid-configuration`.

**Comment by ivankatliarchuk** [comment]
Hi. Feel free to submit an MR

**Comment by jsonjasn** [comment]
FYI here's a fix: https://gitlab.com/guided-explorations/aws/configure-openid-connect-in-aws/-/issues/3

**Comment by n1ngu** [comment]
I don't think it is technically possible to use a different certificate for each path in a domain.

Inspecting the source code, I think it is more likely that this module stumbled on the same bug I ~~fixed~~ mitigated in my bitbucket-oidc module, which is related to fingerprinting gitlab final cert instead of all certificates in the certificate chain as is advised in AWS IAM documentation.

See
- https://github.com/calidae/terraform-aws-bitbucket-oidc/issues/1
- https://github.com/calidae/terraform-aws-bitbucket-oidc/pull/2
- https://stackoverflow.com/questions/72805530/how-to-not-thumbprint-aws-oidc-provider-rotating-certificate

**Comment by JMSoler7** [comment]
I've opened a pull request to solve this issue based on solution commented by @jaason435
